### ISSUE TITLE
Consume availability?

### ISSUE THREAD

**Issue by 4rombusiness** [dorjoosoft/GodotCafebazaar#1]
Does it support consuming a product like coins etc .,?

And...

Probably unrelated but is tapsell plug-in available for Godot too?
Saw it accidentally in screenshots.

**Comment by dorjoosoft** [comment]
Yes, on purchase success event the consume method is called automatically in plugin purchase flow by now and you can send user to buy it again.
I'll make this method separated on next plugin update.
Tapsell plugin is created too and will be available soon.
