### ISSUE TITLE
question about gdap file

### ISSUE THREAD

**Issue by 4rombusiness** [dorjoosoft/GodotCafebazaar#2]
What does this like do?
`remote=["ir.cafebazaar:poolakey:1.0.0-alpha08"]`

**Comment by dorjoosoft** [comment]
As you can read in [Godot android plugin creating documention](https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html#building-an-android-plugin) that defines a dependency to Cafebazaar poolakey api.
