### ISSUE TITLE
Tapsell for Godot

### ISSUE THREAD

**Issue by OverShifted** [dorjoosoft/GodotCafebazaar#3]
In a screenshot in this repository's readme file; looks like there is a plugin called `Godot Tapsell Plugin`.
I wanted to ask that is this plugin part of this repository? because other than in app payment; I was looking for a way to display ads in my game.

![image](https://user-images.githubusercontent.com/53635046/122639725-bf0e4f00-d110-11eb-9a41-d37cb932fe7c.png)

**Comment by dorjoosoft** [comment]
I'll publish Tapsell plugin in a separate repository in about next 10 days. Rewarded video and native banner are incuded in this version.

**Comment by OverShifted** [comment]
@dorjoosoft That is very cool 👍🏻

**Comment by OverShifted** [comment]
I just wanted to ask again about its development. Is it done? If you put it on GitHub, others can help with it.

**Comment by OverShifted** [comment]
@dorjoosoft ?

**Comment by OverShifted** [comment]
Never mind. I ended up implementing it myself.

https://github.com/OverShifted/GodotTapsell
